name: Android CI
on:
   push: 
      branches: [ master ]
   pull_request:
      branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2.4.0
       - name: Setup Java JDK
         uses: actions/setup-java@v2.5.0
         with:
           distribution: 'adopt'
           java-version: '11'
       - name: Build flavor life
         run: ./gradlew assemblelifeRelease
       - name: Build flavor meme
         run: ./gradlew assemblememeRelease
         
       - name: Sign Life AAB
         id: signlife
         uses: r0adkll/sign-android-release@v1
         with:
          releaseDirectory: app/build/outputs/bundle/lifeRelease/app-life-release.aab
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
       - name: Sign Meme AAB
         id: signmeme
         uses: r0adkll/sign-android-release@v1
         with:
          releaseDirectory: app/build/outputs/bundle/memeRelease/app-meme-release.aab
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
         
       - name: Upload life Bundle
         uses: actions/upload-artifact@v2.3.1
         with:
           name: life
           path: app/build/outputs/bundle/lifeRelease/app-life-release.aab
     
       - name: Upload Meme Bundle
         uses: actions/upload-artifact@v2.3.1
         with:
           name: meme
           path: app/build/outputs/bundle/memeRelease/app-meme-release.aab
