name: Android CI
on:
   push: 
      branches: [ master ]
   pull_request:
      branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2.4.0
       - name: Setup Java JDK
         uses: actions/setup-java@v2.5.0
         with:
           distribution: 'adopt'
           java-version: '11'
       - name: Build flavor life
         run: ./gradlew assemblelifeDebug
       - name: Build flavor meme
         run: ./gradlew assemblememeDebug
       - name: Upload life APK
         uses: actions/upload-artifact@v2.3.1
         with:
           name: life
           path: app/build/outputs/apk/life/debug/app-life-debug.apk
       - name: Upload Meme Apk
         uses: actions/upload-artifact@v2.3.1
         with:
           name: meme
           path: app/build/outputs/apk/meme/debug/app-meme-debug.apk
