name: Android CI
on:
   push: 
      branches: [ master ]
   pull_request:
      branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2.4.0
       - name: Setup Java JDK
         uses: actions/setup-java@v2.5.0
         with:
           distribution: 'adopt'
           java-version: '11'
       - name: Build With Gradle
         run: ./gradlew assembleMemeDebug
       - name: Upload APK
         uses: actions/upload-artifact@v2.3.1
         with:
           name: app
           path: app/build/outputs/apk/debug/life.apk
